-- Instalação do zero. Execute no SQL Editor do seu projeto Supabase
-- (Painel Supabase -> SQL Editor -> New query -> colar e rodar).
--
-- Este arquivo já está no estado final: ele inclui o que as migrações
-- 0002..0008 foram acrescentando. Se o seu banco JÁ existe, não rode este
-- script — aplique os arquivos de supabase/migrations/ na ordem numérica.
--
-- DEPOIS DE RODAR, FALTA UM PASSO: crie seu usuário em Authentication ->
-- Users e acrescente-o à tabela public.oficina_equipe (o comando está no
-- rodapé deste arquivo). Sem isso ninguém enxerga nada — as policies pedem
-- que o usuário esteja nessa lista, e não apenas que esteja logado.

create table if not exists public.checklists (
  id bigint generated by default as identity primary key,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  status text not null default 'recebido'
    check (status in ('recebido', 'em_andamento', 'finalizado', 'entregue')),

  atendente text,

  cliente_nome text not null,
  cliente_telefone text,
  cliente_cpf text,
  cliente_endereco text,
  cliente_cep text,
  cliente_numero text,
  cliente_complemento text,

  veiculo_placa text not null,
  veiculo_marca text,
  veiculo_modelo text,
  veiculo_ano text,
  veiculo_cor text,
  veiculo_km text,
  veiculo_combustivel text,
  veiculo_tipo_combustivel text check (veiculo_tipo_combustivel in ('diesel', 'alcool', 'gasolina')),

  fotos text[] not null default '{}',
  avarias text,
  observacoes text not null
);

create index if not exists checklists_criado_em_idx on public.checklists (criado_em desc);
create index if not exists checklists_status_idx on public.checklists (status);
-- a placa é o campo do login do portal do cliente (rota pública), então é a
-- consulta mais exposta do sistema e a que mais compensa ter índice
create index if not exists checklists_veiculo_placa_idx on public.checklists (veiculo_placa);

-- mantém atualizado_em em dia a cada UPDATE
create or replace function public.set_atualizado_em()
returns trigger as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists checklists_set_atualizado_em on public.checklists;
create trigger checklists_set_atualizado_em
  before update on public.checklists
  for each row execute function public.set_atualizado_em();

-- ---------------------------------------------------------------------------
-- Quem é da oficina
--
-- Não basta estar autenticado. O cadastro público do Supabase pode estar
-- ligado (e a anon key fica visível no bundle do navegador), então "logado"
-- não é a mesma coisa que "da equipe": sem esta lista, qualquer pessoa que
-- criasse uma conta com o próprio e-mail leria, editaria e apagaria todas as
-- O.S. e todos os anexos.
-- ---------------------------------------------------------------------------

create table if not exists public.oficina_equipe (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text,
  criado_em timestamptz not null default now()
);

alter table public.oficina_equipe enable row level security;

-- a lista não é editável pelo app: entra e sai gente pelo painel (service
-- role). Cada um só consegue verificar a si mesmo.
drop policy if exists "equipe_ve_a_si_mesma" on public.oficina_equipe;
create policy "equipe_ve_a_si_mesma"
  on public.oficina_equipe for select
  to authenticated
  using (user_id = (select auth.uid()));

-- security definer: a função precisa ler a tabela sem depender da policy
-- acima, senão vira recursão de RLS.
create or replace function public.eh_da_equipe()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.oficina_equipe e where e.user_id = (select auth.uid())
  );
$$;

revoke all on function public.eh_da_equipe() from public;
grant execute on function public.eh_da_equipe() to authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security das O.S.
-- ---------------------------------------------------------------------------

alter table public.checklists enable row level security;

drop policy if exists "checklists_select_authenticated" on public.checklists;
create policy "checklists_select_authenticated"
  on public.checklists for select
  to authenticated
  using (public.eh_da_equipe());

drop policy if exists "checklists_insert_authenticated" on public.checklists;
create policy "checklists_insert_authenticated"
  on public.checklists for insert
  to authenticated
  with check (public.eh_da_equipe());

drop policy if exists "checklists_update_authenticated" on public.checklists;
create policy "checklists_update_authenticated"
  on public.checklists for update
  to authenticated
  using (public.eh_da_equipe())
  with check (public.eh_da_equipe());

drop policy if exists "checklists_delete_authenticated" on public.checklists;
create policy "checklists_delete_authenticated"
  on public.checklists for delete
  to authenticated
  using (public.eh_da_equipe());

-- ---------------------------------------------------------------------------
-- Bucket privado dos anexos
--
-- O upload vai do navegador DIRETO para o Storage, sem passar por rota nossa:
-- o que vale aqui é a única defesa que não dá para pular pelo cliente.
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('checklist-fotos', 'checklist-fotos', false)
on conflict (id) do nothing;

update storage.buckets
set
  file_size_limit = 10485760, -- 10 MB, o mesmo MAX_ANEXO_MB do lib/anexos.ts
  allowed_mime_types = array[
    'image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/bmp',
    'image/avif', 'image/heic', 'image/heif',
    'application/pdf', 'text/plain', 'text/csv',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.oasis.opendocument.text',
    'application/vnd.oasis.opendocument.spreadsheet'
  ]
where id = 'checklist-fotos';

drop policy if exists "checklist_fotos_select_authenticated" on storage.objects;
create policy "checklist_fotos_select_authenticated"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'checklist-fotos' and public.eh_da_equipe());

drop policy if exists "checklist_fotos_insert_authenticated" on storage.objects;
create policy "checklist_fotos_insert_authenticated"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'checklist-fotos'
    and public.eh_da_equipe()
    -- primeira pasta do caminho é o id da O.S.
    and (storage.foldername(name))[1] ~ '^[0-9]+$'
    -- e a extensão está na lista fechada: um .svg é página executável
    -- servida pelo domínio do Storage
    and name ~* '\.(jpg|jpeg|png|webp|gif|bmp|avif|heic|heif|pdf|txt|csv|doc|docx|xls|xlsx|odt|ods)$'
  );

drop policy if exists "checklist_fotos_delete_authenticated" on storage.objects;
create policy "checklist_fotos_delete_authenticated"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'checklist-fotos' and public.eh_da_equipe());

-- ---------------------------------------------------------------------------
-- ÚLTIMO PASSO: libere o seu usuário (crie-o antes em Authentication -> Users)
--
--   insert into public.oficina_equipe (user_id, email)
--   select id, email from auth.users where email = 'voce@exemplo.com';
--
-- O mesmo comando serve para adicionar outra pessoa da oficina depois.
-- ---------------------------------------------------------------------------
