-- Execute este script no SQL Editor do seu projeto Supabase
-- (Painel Supabase -> SQL Editor -> New query -> colar e rodar)
--
-- Se você já rodou uma versão anterior deste script (tabela já existe),
-- use os arquivos em supabase/migrations/ em vez deste, na ordem numérica.

create table if not exists public.checklists (
  id bigint generated by default as identity primary key,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  status text not null default 'recebido'
    check (status in ('recebido', 'em_andamento', 'finalizado', 'entregue')),

  atendente text,

  cliente_nome text not null,
  cliente_telefone text,
  cliente_cpf text,
  cliente_cep text,
  cliente_numero text,
  cliente_complemento text,

  veiculo_placa text not null,
  veiculo_marca text,
  veiculo_modelo text,
  veiculo_ano text,
  veiculo_cor text,
  veiculo_km text,
  veiculo_combustivel text,
  veiculo_tipo_combustivel text check (veiculo_tipo_combustivel in ('diesel', 'alcool', 'gasolina')),

  fotos text[] not null default '{}',
  avarias text,
  observacoes text not null
);

create index if not exists checklists_criado_em_idx on public.checklists (criado_em desc);
create index if not exists checklists_status_idx on public.checklists (status);

-- mantém atualizado_em em dia a cada UPDATE
create or replace function public.set_atualizado_em()
returns trigger as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists checklists_set_atualizado_em on public.checklists;
create trigger checklists_set_atualizado_em
  before update on public.checklists
  for each row execute function public.set_atualizado_em();

-- Row Level Security: só usuários autenticados (login da equipe) podem acessar
alter table public.checklists enable row level security;

drop policy if exists "checklists_select_authenticated" on public.checklists;
create policy "checklists_select_authenticated"
  on public.checklists for select
  to authenticated
  using (true);

drop policy if exists "checklists_insert_authenticated" on public.checklists;
create policy "checklists_insert_authenticated"
  on public.checklists for insert
  to authenticated
  with check (true);

drop policy if exists "checklists_update_authenticated" on public.checklists;
create policy "checklists_update_authenticated"
  on public.checklists for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "checklists_delete_authenticated" on public.checklists;
create policy "checklists_delete_authenticated"
  on public.checklists for delete
  to authenticated
  using (true);

-- Bucket privado no Storage para as fotos do veículo (registradas no cadastro)
insert into storage.buckets (id, name, public)
values ('checklist-fotos', 'checklist-fotos', false)
on conflict (id) do nothing;

drop policy if exists "checklist_fotos_select_authenticated" on storage.objects;
create policy "checklist_fotos_select_authenticated"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'checklist-fotos');

drop policy if exists "checklist_fotos_insert_authenticated" on storage.objects;
create policy "checklist_fotos_insert_authenticated"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'checklist-fotos');

drop policy if exists "checklist_fotos_delete_authenticated" on storage.objects;
create policy "checklist_fotos_delete_authenticated"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'checklist-fotos');
